### ISSUE TITLE
"o: Open file": Symbol’s function definition is void: org-media-note-get-media-file-by-key

### ISSUE THREAD

**Issue by SpiritInAShell** [yuchen-lea/org-media-note#24] opened 2021-05-01 23:51 UTC
When calling with M+x `org-media-note-hydra/body` I get the message:
`Symbol’s function definition is void: org-media-note-get-media-file-by-key`

**Comment by SpiritInAShell** [comment] 2021-05-02 20:42
It seems, that if I use `M+x mpv-play` to open a file, and then call `org-media-note-hydra/body`, I can control the playback and use the functions like timestamp insertion.

**Comment by yuchen-lea** [comment] 2021-05-17 17:49
Sorry for the late reply. I can't reproduce your issue. 

Have you solved this? If not, can you show me your config?

**Comment by yuchen-lea** [comment] 2021-06-10 07:53
Duplicate of #25

**Closed by yuchen-lea** 2021-06-10 07:53 UTC
