### ISSUE TITLE
step by step instructions?

### ISSUE THREAD

**Issue by tjsheth76** [yuchen-lea/org-media-note#36] opened 2022-04-07 14:56 UTC
Hi- what you've built here looks amazing and potentially perfect for our use case. Thank you for making it available!

However, I'm not experienced with emacs or org-mode so having a really hard time figuring out how to use org-media-note. I've got it installed, along with org-ref as per your recommendation. 

I want to play an online video from a url (the video is in google cloud storage). Is this possible? If so, is there anything that could show me what to do- like step by step instructions or something like that? 

I'd really welcome some help. Once I figure out, I can volunteer to write it up and submit it as an add on to your Readme.org - I think it would help other noobs like me :)

**Comment by tjsheth76** [comment] 2022-04-08 01:27
An update- I've got all of this working now! I'm able to play a youtube video and take synced notes. 

Our use case involves mp4 video files that are stored on Google Cloud Storage. I'm able to play the video from inside org-mode (with the `org-media-note-mpv-smart-play` command) by creating a ["signed url"](https://cloud.google.com/storage/docs/access-control/signed-urls) for the video file. 

BUT, when I try to get back to the functions menu (with the `org-media-note-hydra/body` command) so that I can take synced notes, I'm getting this error:

> Not enough arguments for format string

Any suggestions for how I can dig deeper to figure out what's causing this and how to fix? Or any ideas as to what could be causing this?

**Comment by yuchen-lea** [comment] 2022-05-23 04:52
Happy to hear you've got some progress and sorry for the late reply, I was busy working recently.

I'm not sure what you did…… I can't reproduce the error you raised. 

To take notes for online video: 

1. open the functions menu, press"o" to smart open video file
2. input url
3. wait a little seconds, mpv should start playing videos
4. then open the functions menu, press "i" to insert timestamp
5. insert "- " at the begining of the line, turn it into a list
6. then, no need to open the functions menu. Just press "Alt+Enter" at the end of some list item, a new item with current timestamp should be created. 

![org-media-note](https://user-images.githubusercontent.com/7555085/169745025-ba46930f-9b08-4bf7-adfe-570df454d7ed.gif)

Please let me know if you still have trouble.

**Comment by cjbarroso** [comment] 2022-09-17 16:52
I couldn't figure out how to use this without org-ref and it's easier than it looks:
1. Open the hydra and use 'o', for local or remote content.
2. Content opens and starts playing. Hydra is kept open. Press 'i' to add a note. Then convert this link in the first item of an unordered list adding '-' at the beginning of the line.
3. You may now close the hydra and keep adding new items to the list with <C-Enter>. Each new line will insert the current timestamp being played.
4. I like to set it to auto-pause every time I insert a timestamp, so I can enter my notes without pressure. Then you can reopen the hydra and press <space> to unpause and close it again.

It's a great piece of software, incredibly useful.
Last thing: Better if your system has appropriate configs for each media type.

**Comment by yuchen-lea** [comment] 2022-09-24 03:46
> I couldn't figure out how to use this without org-ref 

Look at `org-media-note-mpv-smart-play`, which is binded to 'o' in hydra:
Conditionally open media file in mpv.
1. When point at a file link, play it in mpv;
2. When citation key found, play the corresponding local media or online media;
3. With a single attachment, file, or url: play it in mpv;
4. With multiple attachments, open the attach dir to select;
5. Else, answer y to find local file to open, n to input URL.

Except the second one, others should work without org-ref.

> I like to set it to auto-pause every time I insert a timestamp

Yes, you can:
<img width="1328" alt="图片" src="https://user-images.githubusercontent.com/7555085/192078515-bb72a5b3-c425-4ac1-905c-76a366af6953.png">

This is my first elisp package and it's quiet a personal use. I'm really happy to hear it's useful for you.

**Closed** 2024-01-31 12:19 UTC
